uv run src/finetune_preference.py \
    --dataset_name Zaid/mole_preference \
    --model_name_or_path Qwen2.5-3B-Instruct-kimi-k2-sft-8192 \
    --learning_rate 5.0e-6 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 2 \
    --max_steps 300 \
    --gradient_accumulation_steps 8 \
    --gradient_checkpointing \
    --eval_strategy steps \
    --eval_steps 100 \
    --save_strategy steps \
    --save_steps 100 \
    --output_dir Qwen2.5-3B-Instruct-kimi-k2-dpo-8192-adapters \
    --no_remove_unused_columns \
    --use_peft \
    --lora_r 32 \
    --lora_alpha 16